In [1]:
using Base
-9.4*sin(pi/3)*1.5+20

7.789041806639414

In [ ]:
using Base
using Plots

using PyPlot

ENV["MPLBACKEND"] = "qt5agg"

P11 = [1.2,3.72]
P12 = [10.6,3.72]
P13 = [20,3.72]
P14 = [29.4,3.72]
P15 = [38.8,3.72]
P21 = [5.9,11.86]
P22 = [15.3,11.86]
P23 = [24.7,11.86]
P24 = [34.1,11.86]
P31 = [1.2,20]
P32 = [10.6,20]
P33 = [20,20]
P34 = [29.4,20]
P35 = [38.8,20]
P41 = [5.9,28.14]
P42 = [15.3,28.14]
P43 = [24.7,28.14]
P44 = [34.1,28.14]
P51 = [1.2,36.28]
P52 = [10.6,36.28]
P53 = [20,36.28]
P54 = [29.4,36.28]
P55 = [38.8,36.28]


# Scenario 1
U1 = [6,6]
U2 = [34,6]
U3 = [34,34]
U4 = [6,34]
U5 = [20,10]
U6 = [20,30]

# Scenario 2
# U1 = [13,16]
# U2 = [20,12]
# U3 = [27,16]
# U4 = [27,24]
# U5 = [20,28]
# U6 = [13,24]

# Scenario 3
# U1 = [10.6,14.5]
# U2 = [15.3,22.7]
# U3 = [5.9,22.7]
# U4 = [34.1,20]
# U5 = [34.1,32.2]
# U6 = [34.1,7.8]

fig, axes = plt.subplots(figsize=(8,8))

axes.set_xlim([0,40])
axes.set_ylim([0,40])
plt.yticks(size=14)
plt.xticks(size=14)

plt.scatter(
    [
        P11[1],
        P12[1],
        P13[1],
        P14[1],
        P15[1],
        P21[1],
        P22[1],
        P23[1],
        P24[1],
        P31[1],
        P32[1],
        P33[1],
        P34[1],
        P35[1],
        P41[1],
        P42[1],
        P43[1],
        P44[1],
        P51[1],
        P52[1],
        P53[1],
        P54[1],
        P55[1]
    ],
    [
        P11[2],
        P12[2],
        P13[2],
        P14[2],
        P15[2],
        P21[2],
        P22[2],
        P23[2],
        P24[2],
        P31[2],
        P32[2],
        P33[2],
        P34[2],
        P35[2],
        P41[2],
        P42[2],
        P43[2],
        P44[2],
        P51[2],
        P52[2],
        P53[2],
        P54[2],
        P55[2]
    ],
    label="LED Array"
)




plt.scatter([U1[1],U2[1],U3[1],U4[1],U5[1],U6[1]],
    [U1[2],U2[2],U3[2],U4[2],U5[2],U6[2]], label="User")

axes.legend(loc="upper left", borderaxespad=0, fontsize=12)
plt.savefig("test.png", bbox_inches="tight", pad_inches = 0.05)
plt.savefig("test.eps", bbox_inches="tight", pad_inches = 0.05)


In [ ]:
using Base
using Plots

using PyPlot

ENV["MPLBACKEND"] = "qt5agg"

P11 = [1.2,3.72]
P12 = [10.6,3.72]
P13 = [20,3.72]
P14 = [29.4,3.72]
P15 = [38.8,3.72]
P21 = [5.9,11.86]
P22 = [15.3,11.86]
P23 = [24.7,11.86]
P24 = [34.1,11.86]
P31 = [1.2,20]
P32 = [10.6,20]
P33 = [20,20]
P34 = [29.4,20]
P35 = [38.8,20]
P41 = [5.9,28.14]
P42 = [15.3,28.14]
P43 = [24.7,28.14]
P44 = [34.1,28.14]
P51 = [1.2,36.28]
P52 = [10.6,36.28]
P53 = [20,36.28]
P54 = [29.4,36.28]
P55 = [38.8,36.28]


# Scenario 1
U1 = [6,6]
U2 = [34,6]
U3 = [34,34]
U4 = [6,34]
U5 = [20,10]
U6 = [20,30]

# Scenario 2
# U1 = [13,16]
# U2 = [20,12]
# U3 = [27,16]
# U4 = [27,24]
# U5 = [20,28]
# U6 = [13,24]

# Scenario 3
# U1 = [10.6,14.5]
# U2 = [15.3,22.7]
# U3 = [5.9,22.7]
# U4 = [34.1,20]
# U5 = [34.1,32.2]
# U6 = [34.1,7.8]

fig, axes = plt.subplots(figsize=(8,8))

axes.set_xlim([0,40])
axes.set_ylim([0,40])
plt.yticks(size=14)
plt.xticks(size=14)

plt.scatter(
    [
        P11[1],
        P12[1],
        P13[1],
        P14[1],
        P15[1],
        P21[1],
        P22[1],
        P23[1],
        P24[1],
        P31[1],
        P32[1],
        P33[1],
        P34[1],
        P35[1],
        P41[1],
        P42[1],
        P43[1],
        P44[1],
        P51[1],
        P52[1],
        P53[1],
        P54[1],
        P55[1]
    ],
    [
        P11[2],
        P12[2],
        P13[2],
        P14[2],
        P15[2],
        P21[2],
        P22[2],
        P23[2],
        P24[2],
        P31[2],
        P32[2],
        P33[2],
        P34[2],
        P35[2],
        P41[2],
        P42[2],
        P43[2],
        P44[2],
        P51[2],
        P52[2],
        P53[2],
        P54[2],
        P55[2]
    ],
    label="LED Array"
)




plt.scatter([U1[1],U2[1],U3[1],U4[1],U5[1],U6[1]],
    [U1[2],U2[2],U3[2],U4[2],U5[2],U6[2]], label="User")

axes.legend(loc="upper left", borderaxespad=0, fontsize=12)
plt.savefig("trajectory.png", bbox_inches="tight", pad_inches = 0.05)
plt.savefig("trajectory.eps", bbox_inches="tight", pad_inches = 0.05)


In [ ]:
using Base

function test(a::Int64; kwargs...)
    println(kwargs[:b])
    b = string(kwargs[:b])
    println(b)
    throw(DomainError(b,"Wrong Value"))
end

test(12,kwargs=34,b=56)

a = string("12")
parse(Int, a)

In [ ]:
using DelimitedFiles

dic = string("test.txt")

m = readdlm(dic)

m[:,2,:]

In [ ]:
using LinearAlgebra
using Base

a = reshape(collect(1:12),4,3)

b = [1,2,3]

d = []
for i in 1:size(a)[1]
    d = push!(d,norm(a[i,:]-b))
end

println(d)

println(size(a)[1])
println(a[1,:])
println(norm(a[1,:]-b))

In [ ]:
using Base
using LinearAlgebra
using Distributions: Uniform
a = [2,3,2,3]

b = 1

c = asin.(b./a)



display(c)

d = rand(Uniform(-180,180))

d = reshape(collect(1:10),5,2)


println(d[1,:][2])


In [3]:
using Base

using LinearAlgebra

a = [1.5,2.0,3.0,0.0,4.0,5.0,6.0,0.0,0.0,0.0,2.0]

aa = filter(!iszero,a)
display(aa)
println(length(aa))

7-element Vector{Float64}:
 1.5
 2.0
 3.0
 4.0
 5.0
 6.0
 2.0

7


In [8]:
using Base

using LinearAlgebra

a = [1,2,3,4,6,4,3,2,1]

b = (1 + 2 
    / (3 + 4))
println(maximum(a))
println(argmax(a))

6
5


In [ ]:
using Base 

s_group = []

a = [1;2;3]



In [7]:
using Base: tan, tand, append!, eachindex, union, intersect, push!, deg2rad
using Core: ArgumentError, throw

export LED_selection

function LED_selection(user,user_num,led,led_num,height,device_height,ψ_c,degorrad)

    # grouping
    s_group = []
    user_group = []

    if degorrad = "deg"
        r = (height - device_height) * tan(ψ_c)
    elseif degorrad = "rad"
        r = (height - device_height) * tand(ψ_c)
    else 
        throw(ArgumentError("Wrong argument type degorrad"))
    end
    # LED mark
    for k in 1:user_num
        s_k = []
        for n in 1:led_num
            if (user[k,1] - led[n,1])^2 + (user[k,2] - led[n,2])^2 <= r^2
                s_k = append!(s_k,n)
                println(1)
            end
        end
        change_remark = 0
        for i in eachindex(s_group)
            if intersect(s_group[i],s_k) != []
                s_group[i] = union(s_group[i],s_k)
                user_group[i] = append!(user_group[i],k)
                change_remark = 1
                break    
            end
        end 
        if change_remark == 0
            s_group = push!(s_group,s_k)
            user_group = push!(user_group,k)
        end
    end

    return s_group, user_group
end

user = [6.0 6.0 0.85;
        34.0 6.0 0.85;
        34.0 34.0 0.85;
        6.0 34.0 0.85;
        20.0 10.0 0.85;
        20.0 30.0 0.85]
user_num = size(user,1)
led = [1.2 3.72 3.95;
    10.6 3.72 3.95;
    20.0 3.72 3.95;
    29.4 3.72 3.95;
    38.8 3.72 3.95;
    5.9 11.86 3.95;
    15.3 11.86 3.95;
    24.7 11.86 3.95;
    34.1 11.86 3.95;
    1.2 20.0 3.95;
    10.6 20.0 3.95;
    20.0 20.0 3.95;
    29.4 20.0 3.95;
    38.8 20.0 3.95;
    5.9 28.14 3.95;
    15.3 28.14 3.95;
    24.7 28.14 3.95;
    34.1 28.14 3.95;
    1.2 36.28 3.95;
    10.6 36.28 3.95;
    20.0 36.28 3.95;
    29.4 36.28 3.95;
    38.8 36.28 3.95]
led_num = size(led,1)
height = 3.95
device_height = 0.85

ψ_c = 60

s_group, user_group = LED_selection(user, user_num, led, led_num, height, device_height, ψ_c)

display(s_group)
display(user_group)
display(led[user_group[1],:])

6-element Vector{Any}:
 Any[1, 2]
 Any[4, 5]
 Any[22, 23]
 Any[19, 20]
 Any[7, 8]
 Any[16, 17]

6-element Vector{Any}:
 1
 2
 3
 4
 5
 6

3-element Vector{Float64}:
 1.2
 3.72
 3.95

1
1
1
1
1
1
1
1
1
1
1
1


In [21]:

println(sqrt(3)/3 * 7.05)
println((4-0.85)*tan(pi/3))
println(sqrt(3)/3 * 9.4)

9.4*sqrt(3)/3/tan(pi/3)+0.85

4.070319397786862
5.455960043841961
5.427092530382482


3.9833333333333343